services:
  my-postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: my-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
    networks:
      - transcendence
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: always

  website:
    depends_on:
      my-postgres:
        condition: service_healthy
    container_name: website
    build: ./website/
    volumes:
      - ./website:/app
      - static-volume:/app/staticfiles
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    environment:
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
    networks:
      - transcendence
    restart: always

  daphne:
    depends_on:
      - website
    container_name: daphne
    build: ./daphne/
    volumes:
      - ./website:/app
    expose:
      - 9000
    environment:
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
    networks:
      - transcendence
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - website
    restart: always
    networks:
      - transcendence
    volumes:
      - static-volume:/app/staticfiles


networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/db-volume
  static-volume: