const translations = {
	en: {
		// INDEX
		title: "Transcendence",
		welcome: "Welcome",
		madeBy: "made by 42 Prague students",
		language: "Language",
		// LOGIN
		usernamePlaceholder: "Your username",
		passwordPlaceholder: "Your password",
		loginEmail: "Login with username",
		loginIntra: "Login with Intra",
		loginOr: "or",
		firstTime: "First time here?",
		createAccount: "Make a new account!",
		// 2FA
		twoFA: "Two-Factor Authentication",
		twoFAPlaceholder: "Enter your 2FA code",
		twoFAVerify: "Verify",
		// DASHBOARD
		play: "Play",
		modeLocal: "Local Player",
		modeRemote: "Remote Player",
		modeAI: "AI Player",
		modeTournamentLocal: "Local Tournament",
		modeTournamentRemote: "Remote Tournament",
		viewProfile: "Profile",
		logout: "Logout",
		// SEARCHING FOR GAME
		searchingForGame: "Searching for game",
		returnToMenu: "Return to menu",
		// REMATCH
		waitingForRematch: "Waiting for rematch",
		// GAME
		hasWon: "has won!",
		buttonReplay: "Replay",
		buttonReplaySwitch: "Replay (switch sides)",
		buttonMenu: "Main Menu",
		// TOURNAMENT
		tournamentCreate: "Create Tournament",
		tournamentName: "Tournament Name",
		tournamentNamePlaceholder: "Enter tournament name",
		tournamentSlots: "Player slots",
		tournamentCreateButton: "Create",
		tournamentJoin: "Join Tournament",
		tournamentJoinButton: "Join",
		tournamentLobby: "Lobby for ",
		tournamentLobbyWait: "Waiting for players to join...",
		tournamentLobbyStartButton: "Start Game",
		tournamentLobbyCancelButton: "Cancel Lobby",
		tournamentWaitingForPlayers: "Waiting for players",
		tournamentCancelLobby: "Cancel",
		tournamentjoinRandom: "Join random lobby",
		tournamentWinner: "Winner winner chicken dinner",
		round: "Round",
		addPlayer: "Add Player",
		provideUsername: "Provide a player's username",
		// PROFILE
		profile: "Profile",
		edit: "Edit",
		setup2FA: "Setup 2FA",
		leftPaddleColor: "Left paddle color",
		rightPaddleColor: "Right paddle color",
		ballColor: "Ball color",
		matchHistory: "Match History",
		local: "Local",
		friendlist: "Friendlist",
		win: "Win",
		loss: "Loss",
		addFriends: "Add Friends",
		addFriendPlaceholder: "Provide friend's username",
		add: "Add",
		addFriend: "Add Friend",
		noGamesYet: "You haven't played any games yet!",
		outgoingRequests: "Outgoing Requests",
		incomingRequests: "Incoming Requests",
		availableFriends: "Available Friends",
		userProfile: "User profile",
		editName: "Edit name",
		editNamePlaceholder: "New username",
		update: "Update",
		changePic: "Change profile picture",
		uploadNewPic: "Upload a new profile picture",
		maxSize: "Maximum size",
		submit: "Submit",
		generateQrCode: "Generate QR code",
		enterPinPlaceholder: "Enter PIN",
		enterPairingPinEnable: "Enter Pairing PIN to Enable 2FA",
		disable2FA: "Disable 2FA",
		enterPairingPinDisable: "Enter Pairing PIN to Disable 2FA",
		noFriends: "You have no friends :(",
		noOutgoingRequests: "You have no outgoing friend requests.",
		noIncomingRequests: "You have no incoming friend requests.",
		// ERROR MESSAGES
		registrationFailed: "Registration failed",
		registrationUnsuccessful: "Your attempt at registration was unsuccessful.",
		loginFailed: "Login failed",
		invalidCredentials: "Invalid username or password",
		// LOCAL PLAY
		localPlayer1TmpUsername: "Player 1 Username",
		localPlayer2TmpUsername: "Player 2 Username",
		localPlayCreate: "Create Local Match",
		localPlayer1TmpUsernamePlaceholder: "Enter player 1 username",
		localPlayer2TmpUsernamePlaceholder: "Enter player 2 username",
		// NOTIFICATIONS
		t_capacityFilled_header: "Error adding player",
		t_capacityFilled_message: "The tournament capacity has been filled.",
		t_uniqueNames_header: "Error adding player",
		t_uniqueNames_message: "Players must have unique names.",
		t_emptyName_header: "Error adding player",
		t_emptyName_message: "Player name cannot be empty.",
		t_notEnoughPlayers_header: "Error creating tournament",
		t_notEnoughPlayers_message: "Not enough players added.",
		t_tournamentError_header: "Error creating tournament",
		t_loginFailed_header: "Login failed",
		t_intraLoginFailed_header: "Intra login failed",
		t_matchInitAI_header: "Error initializing AI match",
		t_matchCreateAI_header: "Error creating AI match",
		t_matchCreateLocal_header: "Error creating local match",
		t_rematchCreateLocal_header: "Error creating local rematch",
		t_requestAccept_header: "Friend Request Accepted",
		t_requestAccept_message: "You have accepted the friend request.",
		t_requestAcceptError_header: "Error accepting friend request",
		t_requestReject_header: "Friend Request Rejected",
		t_requestReject_message: "You have rejected the friend request.",
		t_requestRejectError_header: "Error rejecting friend request",
		t_requestSent_header: "Friend Request",
		t_requestSent_message: "Friend request sent.",
		t_requestSent_header: "Error adding friend",
		t_nameChange_header: "Username Change Successful",
		t_nameChange_message: "You have updated your username.",
		t_nameChangeError_header: "Error changing username",
		t_qrGenError_header: "Error generating QR code",
		t_2faEnable_header: "2FA",
		t_2faEnable_message: "The 2FA settings for this account has been enabled.",
		t_pinSubmitError_header: "Error submitting PIN code",
		t_2faDisable_header: "2FA",
		t_2faDisable_message: "The 2FA settings for this account has been disabled.",
		t_selectFileError_header: "Error",
		t_selectFileError_message: "Please select a file.",
		t_imageDimensionsError_header: "Error",
		t_imageDimensionsError_message: "Image dimensions should not exceed 800x800 px.",
		t_profilePictureUploadError_header: "Error uploading profile picture",
		t_invalidImageFileError_header: "Error",
		t_invalidImageFileError_message: "Invalid image file.",
		t_registrationFailed_header: "Registration failed",
		t_tournamentCanceled_header: "Tournament Canceled",
		t_tournamentCanceled_message: "The creator canceled their tournament.",
		t_tournamentLeaveError_header: "Error leaving tournament",
		t_tournamentCreationError_header: "Error creating tournament",
		t_tournamentJoinError_header: "Error joining tournament",
		t_matchNoLongerOngoing_header: "Error",
		t_matchNoLongerOngoing_message: "The match is no longer ongoing.",
		t_openingWsError: "Error opening websocket",
	},
	cz: {
		// INDEX
		title: "Transcendence",
		welcome: "Vítejte",
		madeBy: "vytvořeno studenty 42 Prague",
		language: "Jazyk",
		// LOGIN
		usernamePlaceholder: "Vaše username",
		passwordPlaceholder: "Vaše heslo",
		loginEmail: "Přihlášení",
		loginIntra: "Přihlášení skrze Intra",
		loginOr: "nebo",
		firstTime: "Jsi tu poprvé?",
		createAccount: "Vytvoř si účet!",
		// 2FA
		twoFA: "Dvoufaktorové ověření",
		twoFAPlaceholder: "Zadejte kód 2FA",
		twoFAVerify: "Ověřit",
		// DASHBOARD
		play: "Hraj",
		modeLocal: "Lokální hráč",
		modeRemote: "Vzdálený hráč",
		modeAI: "AI hráč",
		modeTournamentLocal: "Lokální turnaj",
		modeTournamentRemote: "Online turnaj",
		viewProfile: "Profil",
		logout: "Odhlásit se",
		// SEARCHING FOR GAME
		searchingForGame: "Hledám hru",
		returnToMenu: "Návrat do hlavního menu",
		// REMATCH
		waitingForRematch: "Čekám na protivníka",
		// GAME
		hasWon: "je vítěz!",
		buttonReplay: "Hrát znovu",
		buttonReplaySwitch: "Hrát znovu (vymenit strany)",
		buttonMenu: "Hlavní menu",
		// TOURNAMENT
		tournamentCreate: "Vytvoř turnaj",
		tournamentName: "Název turnaje",
		tournamentNamePlaceholder: "Vlož jméno turnaje",
		tournamentSlots: "Počet hráčů",
		tournamentCreateButton: "Vytvořit",
		tournamentJoin: "Přidej se k turnaji",
		tournamentJoinButton: "Připojit",
		tournamentLobby: "Herní lobby pro ",
		tournamentLobbyWait: "Čekání na ostatní hráče...",
		tournamentLobbyStartButton: "Začít hru",
		tournamentLobbyCancelButton: "Zrušit lobby",
		tournamentWaitingForPlayers: "Čekám na ostatní hráče",
		tournamentCancelLobby: "Zrušit",
		tournamentjoinRandom: "Náhodný turnaj",
		tournamentWinner: "Sláva vítězi!",
		round: "Kolo",
		addPlayer: "Přidat hráče",
		provideUsername: "Vlož jméno hráče",
		// PROFILE
		profile: "Profil",
		edit: "Upravit",
		setup2FA: "Nastavit 2FA",
		leftPaddleColor: "Barva levé pálky",
		rightPaddleColor: "Barva pravé pálky",
		ballColor: "Barva míčku",
		matchHistory: "Historie zápasů",
		local: "Lokál",
		friendlist: "Seznam přátel",
		win: "Výhra",
		loss: "Prohra",
		addFriends: "Přidat přátele",
		addFriendPlaceholder: "Vlož jméno přítele",
		add: "Přidat",
		addFriend: "Přidat přítele",
		noGamesYet: "Ještě jsi žádnou hru nehrál!",
		outgoingRequests: "Odeslané žádosti",
		incomingRequests: "Obdržené žádosti",
		availableFriends: "Dostupní přátelé",
		userProfile: "Profil uživatele",
		editName: "Upravit jméno",
		editNamePlaceholder: "Nové jméno",
		update: "Aktualizovat",
		changePic: "Změnit profilovou fotku",
		uploadNewPic: "Nahrát profilovou fotku",
		maxSize: "Maximální velikost",
		submit: "Odeslat",
		generateQrCode: "Generovat QR kód",
		enterPinPlaceholder: "Vlož PIN",
		enterPairingPinEnable: "Vlož PIN pro zapnutí 2FA",
		disable2FA: "Vypnout 2FA",
		enterPairingPinDisable: "Vlož PIN pro vypnutí 2FA",
		noFriends: "Nemáš žádné přátele :(",
		noOutgoingRequests: "Nemáš žádné odeslané žádosti.",
		noIncomingRequests: "Nemáš žádné příchozí žádosti.",
		// ERROR MESSAGES
		registrationFailed: "Registrace selhala",
		registrationUnsuccessful: "Váš pokus o registraci byl neúspěšný.",
		loginFailed: "Neúspěšné přihlášení",
		invalidCredentials: "Neplatné uživatelské jméno nebo heslo",
		// LOCAL PLAY
		localPlayer1TmpUsername: "Hráč 1 Username",
		localPlayer2TmpUsername: "Hráč 2 Username",
		localPlayCreate: "Vytvoř zápas",
		localPlayer1TmpUsernamePlaceholder: "Vlož username pro hráče 1",
		localPlayer2TmpUsernamePlaceholder: "Vlož username pro hráče 2",
		// NOTIFICATIONS
		t_capacityFilled_header: "Chyba při přidávání hráče",
		t_capacityFilled_message: "Kapacita turnaje již byla naplněna.",
		t_uniqueNames_header: "Chyba při přidávání hráče",
		t_uniqueNames_message: "Hráči musí mít unikátní jména.",
		t_emptyName_header: "Chyba při přidávání hráče",
		t_emptyName_message: "Jméno hráče nesmí být prázdné.",
		t_notEnoughPlayers_header: "Chyba při vytváření turnaje",
		t_notEnoughPlayers_message: "Není přidán dostatek hráčů.",
		t_tournamentError_header: "Chyba při vytváření turnaje",
		t_loginFailed_header: "Neúspěšné přihlášení",
		t_intraLoginFailed_header: "Neúspěšné přihlášení přes Intra",
		t_matchInitAI_header: "Chyba při inicializaci zápasu s AI",
		t_matchCreateAI_header: "Chyba při vytváření zápasu s AI",
		t_matchCreateLocal_header: "Chyba při vytváření lokálního zápasu",
		t_rematchCreateLocal_header: "Chyba při vytváření lokální odvety",
		t_requestAccept_header: "Žádost o přátelství přijata",
		t_requestAccept_message: "Přijali jste žádost o přátelství.",
		t_requestAcceptError_header: "Chyba při přijímání žádosti o přátelství",
		t_requestReject_header: "Žádost o přátelství odmítnuta",
		t_requestReject_message: "Odmítli jste žádost o přátelství.",
		t_requestRejectError_header: "Chyba při odmítání žádosti o přátelství",
		t_requestSent_header: "Žádost o přátelství",
		t_requestSent_message: "Žádost o přátelství byla odeslána.",
		t_nameChange_header: "Změna uživatelského jména úspěšná",
		t_nameChange_message: "Aktualizovali jste své uživatelské jméno.",
		t_nameChangeError_header: "Chyba při změně uživatelského jména",
		t_qrGenError_header: "Chyba při generování QR kódu",
		t_2faEnable_header: "2FA",
		t_2faEnable_message: "Nastavení 2FA pro tento účet bylo aktivováno.",
		t_pinSubmitError_header: "Chyba při zadávání PIN kódu",
		t_2faDisable_header: "2FA",
		t_2faDisable_message: "Nastavení 2FA pro tento účet bylo deaktivováno.",
		t_selectFileError_header: "Chyba",
		t_selectFileError_message: "Vyberte prosím soubor.",
		t_imageDimensionsError_header: "Chyba",
		t_imageDimensionsError_message: "Rozměry obrázku by neměly přesáhnout 800x800 px.",
		t_profilePictureUploadError_header: "Chyba při nahrávání profilového obrázku",
		t_invalidImageFileError_header: "Chyba",
		t_invalidImageFileError_message: "Neplatný soubor obrázku.",
		t_registrationFailed_header: "Registrace selhala",
		t_tournamentCanceled_header: "Turnaj byl zrušen",
		t_tournamentCanceled_message: "Tvůrce turnaje turnaj zrušil.",
		t_tournamentLeaveError_header: "Chyba při opuštění turnaje",
		t_tournamentCreationError_header: "Chyba při vytváření turnaje",
		t_tournamentJoinError_header: "Chyba při připojování k turnaji",
		t_matchNoLongerOngoing_header: "Chyba",
		t_matchNoLongerOngoing_message: "Zápas již neprobíhá.",
		t_openingWsError: "Chyba při otevírání websocketu",

	},
	sk: {
		// INDEX
		title: "Transcendence",
		welcome: "Vitajte",
		madeBy: "vytvorené študentmi 42 Prague",
		language: "Jazyk",
		// LOGIN
		usernamePlaceholder: "Vaše username",
		passwordPlaceholder: "Vaše heslo",
		loginEmail: "Prihlásenie",
		loginIntra: "Prihlásenie cez Intra",
		loginOr: "alebo",
		firstTime: "Si tu prvýkrát?",
		createAccount: "Vytvor si účet!",
		// 2FA
		twoFA: "Dvojfaktorové overenie",
		twoFAPlaceholder: "Zadajte kód 2FA",
		twoFAVerify: "Overiť",
		// DASHBOARD
		play: "Hraj",
		modeLocal: "Lokálny hráč",
		modeRemote: "Vzdialený hráč",
		modeAI: "AI hráč",
		modeTournamentLocal: "Lokálny turnaj",
		modeTournamentRemote: "Online turnaj",
		viewProfile: "Profil",
		logout: "Odhlásiť sa",
		// SEARCHING FOR GAME
		searchingForGame: "Hľadám hru",
		returnToMenu: "Návrat do hlavného menu",
		// REMATCH
		waitingForRematch: "Čakám na protivníka",
		// GAME
		hasWon: "je víťaz!",
		buttonReplay: "Hrať znova",
		buttonReplaySwitch: "Hrát znovu (vymenit strany)",
		buttonMenu: "Hlavné menu",
		// TOURNAMENT
		tournamentCreate: "Vytvor turnaj",
		tournamentName: "Názov turnaja",
		tournamentNamePlaceholder: "Zadaj názov turnaja",
		tournamentSlots: "Počet hráčov",
		tournamentCreateButton: "Vytvoriť",
		tournamentJoin: "Pridaj sa k turnaju",
		tournamentJoinButton: "Pripojiť sa",
		tournamentLobby: "Herné lobby pre ",
		tournamentLobbyWait: "Čakanie na ostatných hráčov...",
		tournamentLobbyStartButton: "Začať hru",
		tournamentLobbyCancelButton: "Zrušiť lobby",
		tournamentWaitingForPlayers: "Čakám na ostatných hráčov",
		tournamentCancelLobby: "Zrušiť",
		tournamentjoinRandom: "Náhodný turnaj",
		tournamentWinner: "Sláva víťazovi!",
		round: "Kolo",
		addPlayer: "Pridať hráča",
		provideUsername: "Vlož meno hráča",
		// PROFILE
		profile: "Profil",
		edit: "Upraviť",
		setup2FA: "Nastaviť 2FA",
		leftPaddleColor: "Farba ľavej pálky",
		rightPaddleColor: "Farba pravej pálky",
		ballColor: "Farba lopty",
		matchHistory: "História zápasov",
		local: "Lokál",
		friendlist: "Zoznam priateľov",
		win: "Výhra",
		loss: "Prehra",
		addFriends: "Pridať priateľov",
		addFriendPlaceholder: "Vložte meno priateľa",
		add: "Pridať",
		addFriend: "Pridať priatele",
		noGamesYet: "Ešte si nehral žiadne hry!",
		outgoingRequests: "Odoslané žiadosti",
		incomingRequests: "Obdržané žiadosti",
		availableFriends: "Dostupní priatelia",
		userProfile: "Profil užívateľa",
		editName: "Upraviť meno",
		editNamePlaceholder: "Nové meno",
		update: "Aktualizovať",
		changePic: "Zmena profilovej fotky",
		uploadNewPic: "Nahratie profilovej fotky",
		maxSize: "Maximálna veľkosť",
		submit: "Odoslať",
		generateQrCode: "Generovanie kódu QR",
		enterPinPlaceholder: "Vloženie PIN",
		enterPairingPinEnable: "Vlož PIN pre zapnutie 2FA",
		disable2FA: "Vypnutie 2FA",
		enterPairingPinDisable: "Vlož PIN pre vypnutie 2FA",
		noFriends: "Nemáš žiadnych priateľov :(",
		noOutgoingRequests: "Nemáš žiadne nevybavené žiadosti.",
		noIncomingRequests: "Nemáš žiadne prichádzajúce požiadavky.",
		// ERROR MESSAGES
		registrationFailed: "Registrácia zlyhala",
		registrationUnsuccessful: "Váš pokus o registráciu bol neúspešný.",
		loginFailed: "Neúspěšné přihlášenie",
		invalidCredentials: "Neplatné užívateľské meno alebo heslo",
		// LOCAL PLAY
		localPlayer1TmpUsername: "Hráč 1 Username",
		localPlayer2TmpUsername: "Hráč 2 Username",
		localPlayCreate: "Vytvor zápas",
		localPlayer1TmpUsernamePlaceholder: "Zadaj username pre hráča 1",
		localPlayer2TmpUsernamePlaceholder: "Zadaj username pre hráča 2",
		// NOTIFICATIONS
		t_capacityFilled_header: "Chyba pri pridávaní hráča",
		t_capacityFilled_message: "Kapacita turnaja je už naplnená.",
		t_uniqueNames_header: "Chyba pri pridávaní hráča",
		t_uniqueNames_message: "Hráči musia mať jedinečné mená.",
		t_emptyName_header: "Chyba pri pridávaní hráča",
		t_emptyName_message: "Meno hráča nesmie byť prázdne.",
		t_notEnoughPlayers_header: "Chyba pri vytváraní turnaja",
		t_notEnoughPlayers_message: "Nie je pridaný dostatočný počet hráčov.",
		t_tournamentError_header: "Chyba pri vytváraní turnaja",
		t_loginFailed_header: "Neúspěšné přihlášenie",
		t_intraLoginFailed_header: "Neúspěšné přihlášenie cez Intra",
		t_matchInitAI_header: "Chyba pri inicializácii zápasu s AI",
		t_matchCreateAI_header: "Chyba pri vytváraní zápasu s AI",
		t_matchCreateLocal_header: "Chyba pri vytváraní lokálneho zápasu",
		t_rematchCreateLocal_header: "Chyba pri vytváraní lokálnej odvety",
		t_requestAccept_header: "Žiadosť o priateľstvo prijatá",
		t_requestAccept_message: "Prijali ste žiadosť o priateľstvo.",
		t_requestAcceptError_header: "Chyba pri prijímaní žiadosti o priateľstvo",
		t_requestReject_header: "Žiadosť o priateľstvo odmietnutá",
		t_requestReject_message: "Odmietli ste žiadosť o priateľstvo.",
		t_requestRejectError_header: "Chyba pri odmietaní žiadosti o priateľstvo",
		t_requestSent_header: "Žiadosť o priateľstvo",
		t_requestSent_message: "Žiadosť o priateľstvo bola odoslaná.",
		t_nameChange_header: "Zmena používateľského mena úspešná",
		t_nameChange_message: "Aktualizovali ste svoje používateľské meno.",
		t_nameChangeError_header: "Chyba pri zmene používateľského mena",
		t_qrGenError_header: "Chyba pri generovaní QR kódu",
		t_2faEnable_header: "2FA",
		t_2faEnable_message: "Nastavenie 2FA pre tento účet bolo aktivované.",
		t_pinSubmitError_header: "Chyba pri zadávaní PIN kódu",
		t_2faDisable_header: "2FA",
		t_2faDisable_message: "Nastavenie 2FA pre tento účet bolo deaktivované.",
		t_selectFileError_header: "Chyba",
		t_selectFileError_message: "Vyberte prosím súbor.",
		t_imageDimensionsError_header: "Chyba",
		t_imageDimensionsError_message: "Rozmery obrázku by nemali presiahnuť 800x800 px.",
		t_profilePictureUploadError_header: "Chyba pri nahrávaní profilového obrázku",
		t_invalidImageFileError_header: "Chyba",
		t_invalidImageFileError_message: "Neplatný súbor obrázku.",
		t_registrationFailed_header: "Registrácia zlyhala",
		t_tournamentCanceled_header: "Turnaj bol zrušený",
		t_tournamentCanceled_message: "Tvorca turnaja turnaj zrušil.",
		t_tournamentLeaveError_header: "Chyba pri opustení turnaja",
		t_tournamentCreationError_header: "Chyba pri vytváraní turnaja",
		t_tournamentJoinError_header: "Chyba pri pripájaní k turnaju",
		t_matchNoLongerOngoing_header: "Chyba",
		t_matchNoLongerOngoing_message: "Zápas už neprebieha.",
		t_openingWsError: "Chyba pri otváraní websocketu",

	}
};

document.addEventListener("DOMContentLoaded", () => {
	const languageButtons = {
		langEN: "en",
		langCZ: "cz",
		langSK: "sk"
	};

	let language = localStorage.getItem("language") || "en";

	const setLanguageHandler = (event) => {
		event.preventDefault();
		language = languageButtons[event.target.id];
		setLanguage(language);
	};

	Object.keys(languageButtons).forEach(id => {
		document.getElementById(id).addEventListener("click", setLanguageHandler);
	});

	setLanguage(language);

	const observer = new MutationObserver(() => {
		applyTranslations(language);
	});

	observer.observe(document.body, { childList: true, subtree: true });
});

function applyTranslations(language) {
	document.querySelectorAll("[data-translate]").forEach(element => {
		const key = element.getAttribute("data-translate");
		if (element.tagName === "INPUT" && element.hasAttribute("placeholder")) {
			element.setAttribute("placeholder", translations[language][key] || translations['en'][key]);
		} else {
			element.textContent = translations[language][key] || translations['en'][key];
		}
	});
}

function setLanguage(language) {
	applyTranslations(language);
	localStorage.setItem("language", language);
}