# Generated by Django 5.1.1 on 2024-10-18 09:21

import login.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=login.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loss_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('OFF', 'Offline'), ('ON', 'Online'), ('IG', 'In game'), ('IT', 'In tournament')], default='OFF', max_length=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='win_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
