# Generated by Django 5.1.1 on 2024-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='default_ball_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='default_paddle_height',
            field=models.PositiveIntegerField(default=10.0),
        ),
        migrations.AddField(
            model_name='match',
            name='default_paddle_speed',
            field=models.PositiveIntegerField(default=0.2),
        ),
        migrations.AddField(
            model_name='match',
            name='default_paddle_width',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
