# Generated by Django 5.1.1 on 2024-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
