# Generated by Django 5.1.1 on 2025-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtournament',
            name='capacity',
            field=models.PositiveIntegerField(choices=[(0, 'Empty'), (4, 'Small'), (8, 'Medium'), (16, 'Large')], default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.PositiveIntegerField(choices=[(0, 'Empty'), (4, 'Small'), (8, 'Medium'), (16, 'Large')], default=0),
        ),
    ]
