# Generated by Django 5.1.1 on 2024-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_websocketticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('ID', 'Idle'), ('IG', 'In game')], default='ID', max_length=3),
        ),
    ]
