# Generated by Django 5.1.1 on 2024-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tournament_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
