# Generated by Django 5.1.1 on 2024-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_default_ball_size_match_default_paddle_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='default_ball_size',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='default_paddle_height',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='match',
            name='default_paddle_speed',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='match',
            name='default_paddle_width',
            field=models.FloatField(default=2),
        ),
    ]
