# Generated by Django 5.1.1 on 2024-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_match_default_ball_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='default_paddle_speed',
            field=models.FloatField(default=1),
        ),
    ]
