# Generated by Django 5.1.1 on 2024-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('RM', 'Remote'), ('LC', 'Local'), ('AI', 'AI')], default='RM', max_length=2),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_tmp_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_tmp_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='WebSocketTicket',
        ),
    ]
