# Generated by Django 5.1.1 on 2025-01-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tournament_creator_localtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatch',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimatch',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tournament'),
        ),
        migrations.AddField(
            model_name='localmatch',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='localmatch',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tournament'),
        ),
    ]
