# Generated by Django 5.1.1 on 2025-01-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aimatch_round_number_aimatch_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimatch',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='localmatch',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.localtournament'),
        ),
    ]
